# Generated by Django 4.2 on 2025-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_5category_settings_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meltyrankconfiguration',
            options={'ordering': ['melty_membership_type'], 'verbose_name': '会員ランク設定 (ユーザー向け)', 'verbose_name_plural': '会員ランク設定 (ユーザー向け)'},
        ),
        migrations.AlterField(
            model_name='meltyrankconfiguration',
            name='biid_initial_rank',
            field=models.CharField(choices=[('bronze', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('platinum', 'プラチナ'), ('diamond', 'ダイヤモンド')], help_text='MELTY連携ユーザーの初期ランク決定', max_length=20, verbose_name='BIID初期ランク [ユーザー向け]'),
        ),
        migrations.AlterField(
            model_name='meltyrankconfiguration',
            name='melty_membership_type',
            field=models.CharField(choices=[('free', 'MELTY無料会員'), ('premium', 'MELTYプレミアム会員')], help_text='MELTY連携ユーザーの初期ランク決定', max_length=20, unique=True, verbose_name='MELTY会員種別 [ユーザー向け]'),
        ),
        migrations.AlterField(
            model_name='meltyrankconfiguration',
            name='member_id_prefix',
            field=models.CharField(default='S', help_text='ユーザーの会員ID生成ルール', max_length=5, verbose_name='会員ID接頭辞 [ユーザー向け]'),
        ),
        migrations.AlterField(
            model_name='meltyrankconfiguration',
            name='points_expiry_months',
            field=models.IntegerField(default=12, help_text='ユーザーのポイント管理(月)', verbose_name='ポイント有効期限 [ユーザー向け]'),
        ),
        migrations.AlterField(
            model_name='meltyrankconfiguration',
            name='welcome_bonus_points',
            field=models.IntegerField(default=1000, help_text='新規ユーザーへの初期ポイント付与', verbose_name='ウェルカムボーナスポイント [ユーザー向け]'),
        ),
    ]
